[phases.setup]
commands = ["composer install", "npm install"]

[phases.build]
commands = ["npm run build", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[phases.start]
commands = ["php artisan serve --host=0.0.0.0 --port=8000"]
